files:
  - source: /src/locales/en-GB/*.json
    translation: /src/locales/%locale%/%original_file_name%
  - source: /scr/locales/en-GB/*.json
    translation: /src/locales/%locale%/%original_file_name%
